### ISSUE TITLE
Online clustering

### ISSUE THREAD

**Issue by Ekko1992** [wq2012/SpectralCluster#1]
Hi,

Thanks for your great work and sharing your code with us! I've been working in face recognition and person re-identification domain for a while and I think your clustering method is useful for these domain for sure.

I've also read your recent papers, especially the one "LINKS: A HIGH-DIMENSIONAL ONLINE CLUSTERING METHOD". However, I got a bit confused when looking through this repo. I'm just wondering how can we benefit from your algorithm(this repo) to do online clustering? Because I didn't see such process in the demo code. Or, is LINKS a totally different algorithm? 

Anyway, could you please give me some more explanation about your online clustering method mentioned in your paper? Thanks!

**Comment by wq2012** [comment]
Hi,

This repo is for spectral clustering only, which is offline.

LINKS is totally another algorithm, and it's Google's internal algorithm. If you are interested in that algorithm, you should contact memes@google.com, who is the original author of LINKS. However, I don't think he has any open source plans. But you can at least ask.

**Comment by Ekko1992** [comment]
> Hi,
> 
> This repo is for spectral clustering only, which is offline.
> 
> LINKS is totally another algorithm, and it's Google's internal algorithm. If you are interested in that algorithm, you should contact [memes@google.com](mailto:memes@google.com), who is the original author of LINKS. However, I don't think he has any open source plans. But you can at least ask.

Thanks a lot, it's very clear now :)
