### ISSUE TITLE
Input X

### ISSUE THREAD

**Issue by priyankagutte** [wq2012/SpectralCluster#11]
How do we provide the input X if we are having a input as  audio file in the form of .wav . can you please share one example related to this. 

 Thank You

**Comment by wq2012** [comment]
Please read the paper to understand the problem, and check https://github.com/wq2012/awesome-diarization for useful resources.

**Comment by aidosRepoint** [comment]
@priyankagutte  I recommend you to start from the last paragraph of Introduction section, where they explain the flow of the article. Regarding the inputs it's not as simple as feeding the audio signal. Please read:

> The flowchart of our diarization system is provided in Fig. 1. In
> this system, audio signals are first transformed into frames of width
> 25ms and step 10ms, and log-mel-filterbank energies of dimension
> 40 are extracted from each frame as the network input. We build
> sliding windows of a fixed length on these frames, and run the LSTM
> network on each window. The last-frame output of the LSTM is then
> used as the d-vector representation of this sliding window.
