### ISSUE TITLE
Cosine distance for clustering

### ISSUE THREAD

**Issue by rahul7iitk** [wq2012/SpectralCluster#12]
Hi, 
Thanks for the great code. It's mentioned in the file that you have used euclidean distance as similarity measure instead of cosine similarity, as was originally used in the paper. I want to use cosine similarity as the measure for clustering. Can you tell me how can I do that ?
Also I read [here](https://stats.stackexchange.com/questions/299013/cosine-distance-as-similarity-measure-in-kmeans) that cosine similarity and euclidean distance are linearly related. If so, would changing the similarity measure have any changes in the output ?
Thanks for the time.

**Comment by wq2012** [comment]
Check this: https://github.com/FlorianKrey/DNC
