### ISSUE TITLE
How to implement VAD model with GMM?

### ISSUE THREAD

**Issue by kareemamrr** [wq2012/SpectralCluster#13]
The appropriate paper [Speaker Diarization with LSTM](https://arxiv.org/abs/1710.10468) writes that the Voice Activity Detection model is a GMM model using the same PLP features as the i-vector and two full covariance Gaussians. How can I implement this using scikit-learn's GMM class?

**Comment by wq2012** [comment]
We used a pretrained ASR model to generate force alignment for the data to get per-frame speech vs non-speech ground truth. Then you can simply fit a Gaussian to all speech frames, then fit another Gaussian to all non-speech frames.
