### ISSUE TITLE
Log-mel-filterbank feature extraction

### ISSUE THREAD

**Issue by kareemamrr** [wq2012/SpectralCluster#14]
In the paper thr authors state that they extract log-mel-filterbank energies of dimension 40 from each frame of the raw signal for embedding extraction. Does [this](https://python-speech-features.readthedocs.io/en/latest/#python_speech_features.base.logfbank) implementation of the python_speech_features library adequate to be used directly?

**Comment by wq2012** [comment]
I'm not familiar with `python_speech_features` . But seems it does what it should.

You may also consider `librosa.filters.mel`:
https://librosa.github.io/librosa/generated/librosa.filters.mel.html

Then you can take `log(1+x)` to get the log Mel filterbanks.
