### ISSUE TITLE
Is the RowWiseThreshold doing what I think?

### ISSUE THREAD

**Issue by clabornd** [wq2012/SpectralCluster#18]
The paper states:

_Row-wise  Thresholding:   For  each  row,  set  elements smaller than this row’s p-percentile to 0_

So, if p_percentile = 0.95, then we retain the top 5% of affinities and soft-threshold the rest (even if they are high), which seems intuitive to me.

In the code:  

```
row_max = Y.max(axis=1)
row_max = np.expand_dims(row_max, axis=1)
is_smaller = Y < (row_max * self.p_percentile)

Y = (Y * np.invert(is_smaller)) + (Y * self.multiplier * is_smaller)
```

This appears to be retaining anything larger than 0.95 * row_max.  I tested a thresholding like:

```
row_percentile = np.percentile(Y, self.p_percentile*100, axis = 1)
row_percentile = np.expand_dims(row_percentile, axis = 1)
is_smaller = Y < row_percentile
```

And it seems to alleviate some issues I was having with returning very low #'s of speakers and extreme sensitivity to the p_percentile parameter.

Let me know if I am confused.

**Comment by wq2012** [comment]
You are very correct!

The previous code did not implement the actual percentile-based thresholding.

We actually tried both row_max based and percentile based thresholding. Didn't  see a clear winner. And I agree with you that sometimes percentile based threshold is better than row_max based thresholding. The best results in our paper was using row_max based thresholding, but apparently we forgot to mention that in the paper.

Anyway, I added both options in the code with the `thresholding_with_row_max` boolean argument.

Thanks a lot for reporting this bug.
