### ISSUE TITLE
Run spectral clustering on GPUs

### ISSUE THREAD

**Issue by xinli94** [wq2012/SpectralCluster#2]
Hi,

I am wondering if it is possible to run spectral clustering on GPUs to speed it up. Is there any suggestion on it?

Best,
Xin

**Comment by wq2012** [comment]
This Python library is just a demonstration of how the algorithm is like. This is not the real implementation we use at Google. The Google version is implemented in C++ using MapReduce.

If you want to use this algorithm on GPU, unfortunately you will most likely have to implement it yourself.
