### ISSUE TITLE
Normalization does not preserve Symmetry

### ISSUE THREAD

**Issue by dariocazzani** [wq2012/SpectralCluster#20]
Hi, 
The last step of the Affinity Matrix Refinement does not preserve symmetry.
Yet in your paper you state:
> Symmetrization restores matrix symmetry which is crucial to the spectral clustering algorithm.

This sounds counterintuitive.

**Comment by wq2012** [comment]
That's true. Carlton implemented this part but seems he's not on GitHub.

I think his original thought is, thresholding will largely destroy symmetry, so he used symmetrization right after it.

Compared with thresholding, although normalization will also change the symmetry, but its effect is much smaller.

We didn't try to add another symmetrization after normalization, but I think it won't be harmful.
