### ISSUE TITLE
Another question about the Laplacian used

### ISSUE THREAD

**Issue by vadimkantorov** [wq2012/SpectralCluster#21]
Hi!

You addressed this question in the Q&A, but could you please expand how exactly replacing the diagonal by row-wise max makes the similarity matrix to have the same properties as standard [laplacian matrices](https://en.wikipedia.org/wiki/Laplacian_matrix)? (or maybe it holds approximately and you consider the graph approximately regular after applying thresholding so that row-wise sums are equal between vertices? although it seems it would not hold true if speaking time vastly differs between speakers)

In unnormalized laplacian definition, we subtract from the diagonal the row-wise sums (given non-negative affinity) (and then negate the whole thing).

Maybe a related reference: https://arxiv.org/abs/1712.03769

Thank you!

**Comment by wq2012** [comment]
Yeah, it's an approximation.

We didn't theoretically prove it. But our numerical simulations based on a large number of randomly generated data have shown that our matrix (new diagonal is the maximal non-diagonal element in each row) have similar properties to a standard Laplacian matrix.

**The number of connected components in the graph equals to the number of eigenvalues that are significantly larger than 0.**

Besides, our matrix is more robust to Gaussian blurring. That's the reason we use this non-standard Laplacian.
