### ISSUE TITLE
Segment size and window step matching problem

### ISSUE THREAD

**Issue by Turan111** [wq2012/SpectralCluster#3]
According to the appropriate paper for speaker diarization maximum segment size is 400 ms, window size is 240 ms and window step is 120 ms. For this case we have two windows in one segment and non-covered part 40 ms. (400ms - (240ms +120 ms) = 40 ms). If we add next window we get segment size 480 ms. My question is how to include this uncovered part 40 ms? Or we should take maximum segment size 360 ms?

**Comment by wq2012** [comment]
> For this case we have two windows in one segment

That's not true. A segment does NOT need to **fully** cover a window. As long as more than half of the window is covered by a segment, we count it into this segment. So usually a segment has about 4 windows.

You can also simplify the logic to: as long as the end of the window falls into the segment, we count it into this segment. (changing `end` to `start` or `center` will also work)

**Comment by Turan111** [comment]
Many thanks for the clarification
