### ISSUE TITLE
Configs from your ICASSP 2018 paper

### ISSUE THREAD

**Issue by chonghaozhang1998** [wq2012/SpectralCluster#36]
I want to know when I use the following code
> from spectralcluster import configs
> labels = configs.icassp2018_clusterer.predict(X)

Will all the settings such as refinement operations, affinity matrix, laplacian matrix and so on be configured just as you did in  [your ICASSP 2018 paper](https://google.github.io/speaker-id/publications/LstmDiarization/) or not ?
Do I need to use code to config refinement operations and many others, after using the above code, when I want to get the configs in  [your ICASSP 2018 paper](https://google.github.io/speaker-id/publications/LstmDiarization/) ?

**Comment by wq2012** [comment]
Hi Chonghao,

Thanks for your interest in our work.

> Will all the settings such as refinement operations, affinity matrix, laplacian matrix and so on be configured just as you did in your ICASSP 2018 paper or not ?

It won't be exactly the same, as our paper is based on an internal implemented based on C++. This Python library is an attempt to reimplement everything in Python. So there will always be some minor differences. However, we are trying our best to make sure the Python and C++ implementations are as close as possible.

Other than the implementation differences, the configs of `configs.icassp2018_clusterer` should be the same the the ICASSP 2018 paper.

> Do I need to use code to config refinement operations and many others, after using the above code, when I want to get the configs in your ICASSP 2018 paper ?

You don't. By calling `configs.icassp2018_clusterer`, you immediately get the same config as the ICASSP 2018 paper. No need to specify other parameters.

However, I also want to highlight that this config is only optimized for our own d-vector system. It may not work well for other speaker embedding systems.

**Comment by chonghaozhang1998** [comment]
Thanks a lot!!!!!
