### ISSUE TITLE
Question about this formula in paper mentioned 

### ISSUE THREAD

**Issue by CreativeSelf0** [wq2012/SpectralCluster#37]
![image](https://user-images.githubusercontent.com/18738089/150695337-ca207262-db55-43fe-8ac0-25b9803f09e0.png)
Can you please explain this formula in your paper (SPEAKER DIARIZATION WITH LSTM).

To simply things further, 
Assume I have a Matrix A (m x n) , where m is the number of segments, and n is an embedding for each segment.

Now, I want to know how can I determine k (number of clusters, or number of speakers if you will).

Any ideas? 

Thanks in advance.

**Comment by wq2012** [comment]
Hi, this is nothing fancy but the very basic "elbow rule" of clustering algorithms.

When you increase k, MSCD first drops slowly, and at a certain k, it drops drastically, then it will drop slowly again.

The elbow rule finds the k where it drops drastically.

And find that k by the derivative.

**Comment by CreativeSelf0** [comment]
> 

Thank you very much.
Your work is valuable to the community much appreciated!
