### ISSUE TITLE
UnboundLocalError: local variable 'best_p_percentile_index' referenced before assignment

### ISSUE THREAD

**Issue by hbredin** [wq2012/SpectralCluster#38]
FYI, while running your `pyannote.audio` [PR](https://github.com/pyannote/pyannote-audio/pull/995), I got the following error that I have yet to narrow down.

```
  File "../site-packages/spectralcluster/spectral_clusterer.py", line 181, in predict
    eigenvectors, n_clusters, _ = self.autotune.tune(p_percentile_to_ratio)
  File "../site-packages/spectralcluster/autotune.py", line 96, in tune
    start_index = max(0, best_p_percentile_index - local_search_dist)
UnboundLocalError: local variable 'best_p_percentile_index' referenced before assignment
```

https://github.com/wq2012/SpectralCluster/blob/06504bd15890d21380cab0ff9b80cd437d1402a1/spectralcluster/autotune.py#L96

It probably is because the pipeline tries to cluster a small (like less than 2) number of embeddings but I will confirm this once I know more.

In the meantime, maybe it is obvious to you why this might happen?

**Comment by wq2012** [comment]
Fixed. Now you can pass in `fallback_options` as an additional argument.
