### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by grotos** [wq2012/SpectralCluster#4]
Can anyone give example how to use algorithm? What is X? How to read wav file to X array?

**Comment by wq2012** [comment]
You use it the same way as you use any scikit-learn clustering algorithm: https://scikit-learn.org/stable/modules/clustering.html

X is data, which is clearly explained in the README.md file.

You don't feed wav file to it. You need to use another library to extract speaker-discriminative embeddings from sliding windows before clustering. See this link for resources: https://github.com/wq2012/awesome-diarization

**Comment by CarmiShimon** [comment]
Is there any written script that does all the embedding calculations? 
Sliding windows, lstm, etc.?

**Comment by wq2012** [comment]
@CarmiShimon There may exist some open source implementations, but I don't know any of them.

**Comment by CarmiShimon** [comment]
Thanks!
Well, that's kind of sad since also here [(https://github.com/google/uis-rnn)] there is no explanation on how to prepare a train or test sequences.

**Comment by wq2012** [comment]
@CarmiShimon It is indeed very unfortunate! Like many other big companies, most of our internal codebase has heavy dependencies on millions of internal libraries. Open sourcing any codebase that were not originally designed for open source would be nearly impossible.

Even for uis-rnn, where open source was originally planned, it still took us months to get it on GitHub.

**Comment by salisbury-espinosa** [comment]
> @CarmiShimon There may exist some open source implementations, but I don't know any of them.

https://github.com/pyannote/pyannote-audio ;)

**Comment by AigizK** [comment]
https://medium.com/saarthi-ai/who-spoke-when-build-your-own-speaker-diarization-module-from-scratch-e7d725ee279
