### ISSUE TITLE
Threshold used for Agglomerative fallback clusterer

### ISSUE THREAD

**Issue by hbredin** [wq2012/SpectralCluster#40]
How does one provide a threshold for Agglomerative fallback clusterer?

https://github.com/wq2012/SpectralCluster/blob/b6e11827e30e83eedba3f7f659ee634a25095eb6/spectralcluster/fallback_clusterer.py#L109

and is the threshold applied on the raw cosine distance or the affinity?

**Comment by wq2012** [comment]
I can add it.

**Comment by wq2012** [comment]
Also, if you have a good threshold for AHC, maybe we should use even larger number for `spectral_min_embeddings`, something like 20.

I just found out that spectral clustering is really not good when the number of embeddings is small.
