### ISSUE TITLE
How to not use any single_cluster_condition?

### ISSUE THREAD

**Issue by hbredin** [wq2012/SpectralCluster#41]
I am having trouble getting any good results with existing built-in `single_cluster_condition`.

Therefore, I'd like to try and deactivate it completely.
Is there an option for that? 

https://github.com/wq2012/SpectralCluster/blob/b6e11827e30e83eedba3f7f659ee634a25095eb6/spectralcluster/fallback_clusterer.py#L55

**Comment by wq2012** [comment]
Just set min_clusters != 1?

**Comment by wq2012** [comment]
Or use single_cluster_condition=AllAffinity, and set single_cluster_affinity_threshold to a big number?

**Comment by hbredin** [comment]
Thanks.
