### ISSUE TITLE
Is autotune useful when the number of clusters is known in advance?

### ISSUE THREAD

**Issue by hbredin** [wq2012/SpectralCluster#42]
There exists a scenario where the expected number of clusters is known in advance.

Under this assumption, my first intuition was that I should **not** use `autotune` and simply set `min_clusters = max_clusters = expected_num_clusters`.  

However, after looking a bit closer to the code, I am wondering whether it might still be a good idea to use it when `RowWiseThreshold` refinement is active. 

Even for a fixed number of clusters, the value of `p_percentile` might have an influence on the resulting clusters, right?

However, it looks like (*correct me if I am wrong, I might have overlooked something*) that there is no way to autotune the value of `p_percentile` under the constraint that the number of clusters is fixed.

**Comment by hbredin** [comment]
`autotune` does run even when `min_clusters = max_clusters`.

However, it looks like [`compute_number_of_clusters`](https://github.com/wq2012/SpectralCluster/blob/8c7e68edb454b1f1a19fe0ee9c34405d09457669/spectralcluster/utils.py#L71) only takes `max_clusters` into account and could therefore return `n_clusters < max_clusters`, even though `min_clusters = max_clusters`.

**Comment by wq2012** [comment]
Yeah that's intentional.

min_clusters is applied after eigen-gap:
https://github.com/wq2012/SpectralCluster/blob/8c7e68edb454b1f1a19fe0ee9c34405d09457669/spectralcluster/spectral_clusterer.py#L214

Does this cause any issues?

**Comment by hbredin** [comment]
No, it does not cause any issues.

I was just wondering whether the selected `p_percentile` would be different if it was optimized for a specific `num_clusters` rather than a `max_clusters` upper bound.

Closing as I am probably over-thinking this :-)

**Comment by wq2012** [comment]
That's an interesting question. We never tried that.

The proxy metric for auto-tune is defined based on p and eigen gap. If you set max_clusters for the auto-tune, you are tuning with a fix index for find the eigen-gap, instead of the "optimal" eigen gap (still constrained by max_clusters though).

If you want to try this out, I can add a parameter to the options.
