### ISSUE TITLE
Is there a way to monitor the progress of the predict() method?

### ISSUE THREAD

**Issue by paulsingh** [wq2012/SpectralCluster#45]
The `predict()` method's code seems pretty straightforward. I'm curious though, has anyone else found a way to monitor the progress of the method when processing larger amounts of data? (I'm running SpectralCluster as a background queue/job and wondering how to differentiate a stalled process from a long-running process.)

**Comment by wq2012** [comment]
It's slow because `np.linalg.eig` is slow on big matrix. Since `np.linalg.eig` does not provide a way to monitor it, so it's not feasible unfortunately.
